rm(list=ls()); gc()
setwd("C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project")
dat =read.table("cleaned_pokedex.csv",sep=",",header=TRUE)

dat = subset(dat, select = -c(X))

# table(dat$Viability) # take a look at how many acceptance and rejection first
min.model = glm(Viability ~ 1, data = dat, family = 'binomial') #Only Include the intercept
max.model = glm(Viability ~ ., data = dat, family = 'binomial') #Include everything in the model
max.formula = formula(max.model)

# tell R that these are categorical variables
dat$Viability = as.factor(dat$Viability) 

dat$Type_Bug = as.factor(dat$Type_Bug)
dat$Type_Dark = as.factor(dat$Type_Dark)
dat$Type_Electric = as.factor(dat$Type_Electric)
dat$Type_Fairy = as.factor(dat$Type_Fairy)
dat$Type_Fighting = as.factor(dat$Type_Fighting)
dat$Type_Fire = as.factor(dat$Type_Fire)
dat$Type_Flying = as.factor(dat$Type_Flying)
dat$Type_Ghost = as.factor(dat$Type_Ghost)
dat$Type_Grass = as.factor(dat$Type_Grass)
dat$Type_Ground = as.factor(dat$Type_Ground)
dat$Type_Poison = as.factor(dat$Type_Poison)
dat$Type_Psychic = as.factor(dat$Type_Psychic)
dat$Type_Rock = as.factor(dat$Type_Rock)
dat$Type_Steel = as.factor(dat$Type_Steel)
dat$Type_Water = as.factor(dat$Type_Water)
dat$Type_Dragon = as.factor(dat$Type_Dragon)
dat$Type_Ice = as.factor(dat$Type_Ice)
dat$Type_Normal = as.factor(dat$Type_Normal)

dat$Ability_Zen.Mode = as.factor(dat$Ability_Zen.Mode)
dat$Ability_Adaptability = as.factor(dat$Ability_Adaptability)
dat$Ability_Download = as.factor(dat$Ability_Download)
dat$Ability_Analytic = as.factor(dat$Ability_Analytic)
dat$Ability_Aerilate = as.factor(dat$Ability_Aerilate)
dat$Ability_Aftermath = as.factor(dat$Ability_Aftermath)
dat$Ability_Unburden = as.factor(dat$Ability_Unburden)
dat$Ability_Flare.Boost = as.factor(dat$Ability_Flare.Boost)
dat$Ability_Air.Lock = as.factor(dat$Ability_Air.Lock)
dat$Ability_Anger.Point = as.factor(dat$Ability_Anger.Point)
dat$Ability_Shell.Armor = as.factor(dat$Ability_Shell.Armor)
dat$Ability_Regenerator = as.factor(dat$Ability_Regenerator)
dat$Ability_Anticipation = as.factor(dat$Ability_Anticipation)
dat$Ability_Overcoat = as.factor(dat$Ability_Overcoat)
dat$Ability_Dry.Skin = as.factor(dat$Ability_Dry.Skin)
dat$Ability_Poison.Touch = as.factor(dat$Ability_Poison.Touch)
dat$Ability_Frisk = as.factor(dat$Ability_Frisk)
dat$Ability_Speed.Boost = as.factor(dat$Ability_Speed.Boost)
dat$Ability_Aroma.Veil = as.factor(dat$Ability_Aroma.Veil)
dat$Ability_Gluttony = as.factor(dat$Ability_Gluttony)
dat$Ability_Thick.Fat = as.factor(dat$Ability_Thick.Fat)
dat$Ability_As.One = as.factor(dat$Ability_As.One)
dat$Ability_Aura.Break = as.factor(dat$Ability_Aura.Break)
dat$Ability_Power.Construct = as.factor(dat$Ability_Power.Construct)
dat$Ability_Bad.Dreams = as.factor(dat$Ability_Bad.Dreams)
dat$Ability_Ball.Fetch = as.factor(dat$Ability_Ball.Fetch)
dat$Ability_Rattled = as.factor(dat$Ability_Rattled)
dat$Ability_Battery = as.factor(dat$Ability_Battery)
dat$Ability_Battle.Armor = as.factor(dat$Ability_Battle.Armor)
dat$Ability_Defiant = as.factor(dat$Ability_Defiant)
dat$Ability_Swift.Swim = as.factor(dat$Ability_Swift.Swim)
dat$Ability_Sniper = as.factor(dat$Ability_Sniper)
dat$Ability_Keen.Eye = as.factor(dat$Ability_Keen.Eye)
dat$Ability_Tough.Claws = as.factor(dat$Ability_Tough.Claws)
dat$Ability_Steely.Spirit = as.factor(dat$Ability_Steely.Spirit)
dat$Ability_Battle.Bond = as.factor(dat$Ability_Battle.Bond)
dat$Ability_Beads.of.Ruin = as.factor(dat$Ability_Beads.of.Ruin)
dat$Ability_Beast.Boost = as.factor(dat$Ability_Beast.Boost)
dat$Ability_Beserk = as.factor(dat$Ability_Beserk)
dat$Ability_Sap.Sipper = as.factor(dat$Ability_Sap.Sipper)
dat$Ability_Cloud.Nine = as.factor(dat$Ability_Cloud.Nine)
dat$Ability_Big.Pecks = as.factor(dat$Ability_Big.Pecks)
dat$Ability_Gale.Wings = as.factor(dat$Ability_Gale.Wings)
dat$Ability_Rocky.Payload = as.factor(dat$Ability_Rocky.Payload)
dat$Ability_Weak.Armor = as.factor(dat$Ability_Weak.Armor)
dat$Ability_Super.Luck = as.factor(dat$Ability_Super.Luck)
dat$Ability_Rivalry = as.factor(dat$Ability_Rivalry)
dat$Ability_Blaze = as.factor(dat$Ability_Blaze)
dat$Ability_Flash.Fire = as.factor(dat$Ability_Flash.Fire)
dat$Ability_Intimidate = as.factor(dat$Ability_Intimidate)
dat$Ability_Iron.Fist = as.factor(dat$Ability_Iron.Fist)
dat$Ability_Libero = as.factor(dat$Ability_Libero)
dat$Ability_Magician = as.factor(dat$Ability_Magician)
dat$Ability_Reckless = as.factor(dat$Ability_Reckless)
dat$Ability_Solar.Power = as.factor(dat$Ability_Solar.Power)
dat$Ability_Unaware = as.factor(dat$Ability_Unaware)
dat$Ability_Bulletproof = as.factor(dat$Ability_Bulletproof)
dat$Ability_Soundproof = as.factor(dat$Ability_Soundproof)
dat$Ability_Cheek.Pouch = as.factor(dat$Ability_Cheek.Pouch)
dat$Ability_Pickup = as.factor(dat$Ability_Pickup)
dat$Ability_Plus = as.factor(dat$Ability_Plus)
dat$Ability_Chilling.Neigh = as.factor(dat$Ability_Chilling.Neigh)
dat$Ability_Chlorophyll = as.factor(dat$Ability_Chlorophyll)
dat$Ability_Effect.Spore = as.factor(dat$Ability_Effect.Spore)
dat$Ability_Harvest = as.factor(dat$Ability_Harvest)
dat$Ability_Healer = as.factor(dat$Ability_Healer)
dat$Ability_Run.Away = as.factor(dat$Ability_Run.Away)
dat$Ability_Stench = as.factor(dat$Ability_Stench)
dat$Ability_Early.Bird = as.factor(dat$Ability_Early.Bird)
dat$Ability_Pickpocket = as.factor(dat$Ability_Pickpocket)
dat$Ability_Hustle = as.factor(dat$Ability_Hustle)
dat$Ability_Leaf.Guard = as.factor(dat$Ability_Leaf.Guard)
dat$Ability_Insomnia = as.factor(dat$Ability_Insomnia)
dat$Ability_Klutz = as.factor(dat$Ability_Klutz)
dat$Ability_Moody = as.factor(dat$Ability_Moody)
dat$Ability_Infiltrator = as.factor(dat$Ability_Infiltrator)
dat$Ability_Own.Tempo = as.factor(dat$Ability_Own.Tempo)
dat$Ability_Serene.Grace = as.factor(dat$Ability_Serene.Grace)
dat$Ability_Wind.Rider = as.factor(dat$Ability_Wind.Rider)
dat$Ability_Clear.Body = as.factor(dat$Ability_Clear.Body)
dat$Ability_Ice.Body = as.factor(dat$Ability_Ice.Body)
dat$Ability_Light.Metal = as.factor(dat$Ability_Light.Metal)
dat$Ability_Sturdy = as.factor(dat$Ability_Sturdy)
dat$Ability_Cursed.Body = as.factor(dat$Ability_Cursed.Body)
dat$Ability_Liquid.Ooze = as.factor(dat$Ability_Liquid.Ooze)
dat$Ability_Rain.Dish = as.factor(dat$Ability_Rain.Dish)
dat$Ability_Color.Change = as.factor(dat$Ability_Color.Change)
dat$Ability_Protean = as.factor(dat$Ability_Protean)
dat$Ability_Comatose = as.factor(dat$Ability_Comatose)
dat$Ability_Commander = as.factor(dat$Ability_Commander)
dat$Ability_Storm.Drain = as.factor(dat$Ability_Storm.Drain)
dat$Ability_Competitive = as.factor(dat$Ability_Competitive)
dat$Ability_Compound.Eyes = as.factor(dat$Ability_Compound.Eyes)
dat$Ability_Shed.Skin = as.factor(dat$Ability_Shed.Skin)
dat$Ability_Tinted.Lens = as.factor(dat$Ability_Tinted.Lens)
dat$Ability_Unnerve = as.factor(dat$Ability_Unnerve)
dat$Ability_Swarm = as.factor(dat$Ability_Swarm)
dat$Ability_Contrary = as.factor(dat$Ability_Contrary)
dat$Ability_Suction.Cups = as.factor(dat$Ability_Suction.Cups)
dat$Ability_Corrosion = as.factor(dat$Ability_Corrosion)
dat$Ability_Oblivious = as.factor(dat$Ability_Oblivious)
dat$Ability_Cotton.Down = as.factor(dat$Ability_Cotton.Down)
dat$Ability_Cud.Chew = as.factor(dat$Ability_Cud.Chew)
dat$Ability_Armor.Tail = as.factor(dat$Ability_Armor.Tail)
dat$Ability_Curious.Medicine = as.factor(dat$Ability_Curious.Medicine)
dat$Ability_Lightning.Rod = as.factor(dat$Ability_Lightning.Rod)
dat$Ability_Rock.Head = as.factor(dat$Ability_Rock.Head)
dat$Ability_Cute.Charm = as.factor(dat$Ability_Cute.Charm)
dat$Ability_Pixilate = as.factor(dat$Ability_Pixilate)
dat$Ability_Friend.Guard = as.factor(dat$Ability_Friend.Guard)
dat$Ability_Limber = as.factor(dat$Ability_Limber)
dat$Ability_Magic.Guard = as.factor(dat$Ability_Magic.Guard)
dat$Ability_Normalize = as.factor(dat$Ability_Normalize)
dat$Ability_Wonder.Skin = as.factor(dat$Ability_Wonder.Skin)
dat$Ability_Technician = as.factor(dat$Ability_Technician)
dat$Ability_Skill.Link = as.factor(dat$Ability_Skill.Link)
dat$Ability_Damp = as.factor(dat$Ability_Damp)
dat$Ability_Water.Absorb = as.factor(dat$Ability_Water.Absorb)
dat$Ability_Dancer = as.factor(dat$Ability_Dancer)
dat$Ability_Dark.Aura = as.factor(dat$Ability_Dark.Aura)
dat$Ability_Daunltess.Shield = as.factor(dat$Ability_Daunltess.Shield)
dat$Ability_Dazzling = as.factor(dat$Ability_Dazzling)
dat$Ability_Strong.Jaw = as.factor(dat$Ability_Strong.Jaw)
dat$Ability_Defeatist = as.factor(dat$Ability_Defeatist)
dat$Ability_Inner.Focus = as.factor(dat$Ability_Inner.Focus)
dat$Ability_Pressure = as.factor(dat$Ability_Pressure)
dat$Ability_Supeme.Overlord = as.factor(dat$Ability_Supeme.Overlord)
dat$Ability_Delta.Stream = as.factor(dat$Ability_Delta.Stream)
dat$Ability_Desolate.Land = as.factor(dat$Ability_Desolate.Land)
dat$Ability_Disguise = as.factor(dat$Ability_Disguise)
dat$Ability_Dragon.s.Maw = as.factor(dat$Ability_Dragon.s.Maw)
dat$Ability_Drizzle = as.factor(dat$Ability_Drizzle)
dat$Ability_Drought = as.factor(dat$Ability_Drought)
dat$Ability_Sand.Veil = as.factor(dat$Ability_Sand.Veil)
dat$Ability_Scrappy = as.factor(dat$Ability_Scrappy)
dat$Ability_Earth.Eater = as.factor(dat$Ability_Earth.Eater)
dat$Ability_Poison.Heal = as.factor(dat$Ability_Poison.Heal)
dat$Ability_Quick.Feet = as.factor(dat$Ability_Quick.Feet)
dat$Ability_Electirc.Surge = as.factor(dat$Ability_Electirc.Surge)
dat$Ability_Telepathy = as.factor(dat$Ability_Telepathy)
dat$Ability_Electromorphosis = as.factor(dat$Ability_Electromorphosis)
dat$Ability_Static = as.factor(dat$Ability_Static)
dat$Ability_Embody.Aspect = as.factor(dat$Ability_Embody.Aspect)
dat$Ability_Emergency.Exit = as.factor(dat$Ability_Emergency.Exit)
dat$Ability_Fairy.Aura = as.factor(dat$Ability_Fairy.Aura)
dat$Ability_Filter = as.factor(dat$Ability_Filter)
dat$Ability_Flame.Body = as.factor(dat$Ability_Flame.Body)
dat$Ability_Vital.Spirit = as.factor(dat$Ability_Vital.Spirit)
dat$Ability_Guts = as.factor(dat$Ability_Guts)
dat$Ability_White.Smoke = as.factor(dat$Ability_White.Smoke)
dat$Ability_Flower.Gift = as.factor(dat$Ability_Flower.Gift)
dat$Ability_Flower.Veil = as.factor(dat$Ability_Flower.Veil)
dat$Ability_Symbiosis = as.factor(dat$Ability_Symbiosis)
dat$Ability_Triage = as.factor(dat$Ability_Triage)
dat$Ability_Natural.Cure = as.factor(dat$Ability_Natural.Cure)
dat$Ability_Fluffy = as.factor(dat$Ability_Fluffy)
dat$Ability_Steadfast = as.factor(dat$Ability_Steadfast)
dat$Ability_Forecast = as.factor(dat$Ability_Forecast)
dat$Ability_Forewarn = as.factor(dat$Ability_Forewarn)
dat$Ability_Synchronize = as.factor(dat$Ability_Synchronize)
dat$Ability_Shadow.Tag = as.factor(dat$Ability_Shadow.Tag)
dat$Ability_Full.Metal.Body = as.factor(dat$Ability_Full.Metal.Body)
dat$Ability_Fur.Coat = as.factor(dat$Ability_Fur.Coat)
dat$Ability_Overgrow = as.factor(dat$Ability_Overgrow)
dat$Ability_Torrent = as.factor(dat$Ability_Torrent)
dat$Ability_Good.as.Gold = as.factor(dat$Ability_Good.as.Gold)
dat$Ability_Gooey = as.factor(dat$Ability_Gooey)
dat$Ability_Gorilla.Tactics = as.factor(dat$Ability_Gorilla.Tactics)
dat$Ability_Grass.Surge = as.factor(dat$Ability_Grass.Surge)
dat$Ability_Grim.Neigh = as.factor(dat$Ability_Grim.Neigh)
dat$Ability_Gulp.Missile = as.factor(dat$Ability_Gulp.Missile)
dat$Ability_Mold.Breaker = as.factor(dat$Ability_Mold.Breaker)
dat$Ability_No.Guard = as.factor(dat$Ability_No.Guard)
dat$Ability_Sheer.Force = as.factor(dat$Ability_Sheer.Force)
dat$Ability_Hadron.Engine = as.factor(dat$Ability_Hadron.Engine)
dat$Ability_Magic.Bounce = as.factor(dat$Ability_Magic.Bounce)
dat$Ability_Hydration = as.factor(dat$Ability_Hydration)
dat$Ability_Honey.Gather = as.factor(dat$Ability_Honey.Gather)
dat$Ability_Shield.Dust = as.factor(dat$Ability_Shield.Dust)
dat$Ability_Sweet.Veil = as.factor(dat$Ability_Sweet.Veil)
dat$Ability_Hospitality = as.factor(dat$Ability_Hospitality)
dat$Ability_Heatproof = as.factor(dat$Ability_Heatproof)
dat$Ability_Huge.Power = as.factor(dat$Ability_Huge.Power)
dat$Ability_Hunger.Switch = as.factor(dat$Ability_Hunger.Switch)
dat$Ability_Sticky.Hold = as.factor(dat$Ability_Sticky.Hold)
dat$Ability_Hyper.Cutter = as.factor(dat$Ability_Hyper.Cutter)
dat$Ability_Arena.Trap = as.factor(dat$Ability_Arena.Trap)
dat$Ability_Moxie = as.factor(dat$Ability_Moxie)
dat$Ability_Immunity = as.factor(dat$Ability_Immunity)
dat$Ability_Snow.Cloak = as.factor(dat$Ability_Snow.Cloak)
dat$Ability_Snow.Warning = as.factor(dat$Ability_Snow.Warning)
dat$Ability_Ice.Face = as.factor(dat$Ability_Ice.Face)
dat$Ability_Illuminate = as.factor(dat$Ability_Illuminate)
dat$Ability_Sand.Rush = as.factor(dat$Ability_Sand.Rush)
dat$Ability_Prankster = as.factor(dat$Ability_Prankster)
dat$Ability_Illusion = as.factor(dat$Ability_Illusion)
dat$Ability_Toxic.Boost = as.factor(dat$Ability_Toxic.Boost)
dat$Ability_Innards.Out = as.factor(dat$Ability_Innards.Out)
dat$Ability_Multiscale = as.factor(dat$Ability_Multiscale)
dat$Ability_Psychic.Surge = as.factor(dat$Ability_Psychic.Surge)
dat$Ability_Stakeout = as.factor(dat$Ability_Stakeout)
dat$Ability_Justified = as.factor(dat$Ability_Justified)
dat$Ability_Guard.Dog = as.factor(dat$Ability_Guard.Dog)
dat$Ability_Runaway = as.factor(dat$Ability_Runaway)
dat$Ability_Intrepid.Sword = as.factor(dat$Ability_Intrepid.Sword)
dat$Ability_Iron.Barbs = as.factor(dat$Ability_Iron.Barbs)
dat$Ability_Stall = as.factor(dat$Ability_Stall)
dat$Ability_Tangled.Feet = as.factor(dat$Ability_Tangled.Feet)
dat$Ability_Queenly.Majesty = as.factor(dat$Ability_Queenly.Majesty)
dat$Ability_Levitate = as.factor(dat$Ability_Levitate)
dat$Ability_Heavy.Metal = as.factor(dat$Ability_Heavy.Metal)
dat$Ability_Neutralizing.Gas = as.factor(dat$Ability_Neutralizing.Gas)
dat$Ability_Misty.Surge = as.factor(dat$Ability_Misty.Surge)
dat$Ability_Stalwart = as.factor(dat$Ability_Stalwart)
dat$Ability_Electric.Surge = as.factor(dat$Ability_Electric.Surge)
dat$Ability_Motor.Drive = as.factor(dat$Ability_Motor.Drive)
dat$Ability_Solid.Rock = as.factor(dat$Ability_Solid.Rock)
dat$Ability_Imposter = as.factor(dat$Ability_Imposter)
dat$Ability_Lingering.Aroma = as.factor(dat$Ability_Lingering.Aroma)
dat$Ability_Magma.Armor = as.factor(dat$Ability_Magma.Armor)
dat$Ability_Magnet.Pull = as.factor(dat$Ability_Magnet.Pull)
dat$Ability_Galvanize = as.factor(dat$Ability_Galvanize)
dat$Ability_Marvel.Scale = as.factor(dat$Ability_Marvel.Scale)
dat$Ability_Mega.Launcher = as.factor(dat$Ability_Mega.Launcher)
dat$Ability_Merciless = as.factor(dat$Ability_Merciless)
dat$Ability_Mimicry = as.factor(dat$Ability_Mimicry)
dat$Ability_Mind.s.Eye = as.factor(dat$Ability_Mind.s.Eye)
dat$Ability_Minus = as.factor(dat$Ability_Minus)
dat$Ability_Volt.Absorb = as.factor(dat$Ability_Volt.Absorb)
dat$Ability_Sharpness = as.factor(dat$Ability_Sharpness)
dat$Ability_Multitype = as.factor(dat$Ability_Multitype)
dat$Ability_Mummy = as.factor(dat$Ability_Mummy)
dat$Ability_Mycelium.Might = as.factor(dat$Ability_Mycelium.Might)
dat$Ability_Poison.Point = as.factor(dat$Ability_Poison.Point)
dat$Ability_Simple = as.factor(dat$Ability_Simple)
dat$Ability_Opportunist = as.factor(dat$Ability_Opportunist)
dat$Ability_Orichalcum.Pulse = as.factor(dat$Ability_Orichalcum.Pulse)
dat$Ability_Slow.Start = as.factor(dat$Ability_Slow.Start)
dat$Ability_Bullerproof = as.factor(dat$Ability_Bullerproof)
dat$Ability_Grassy.Surge = as.factor(dat$Ability_Grassy.Surge)
dat$Ability_Long.Reach = as.factor(dat$Ability_Long.Reach)
dat$Ability_Stamina = as.factor(dat$Ability_Stamina)
dat$Ability_Parental.Bond = as.factor(dat$Ability_Parental.Bond)
dat$Ability_Power.of.Alchemy = as.factor(dat$Ability_Power.of.Alchemy)
dat$Ability_Power.Spot = as.factor(dat$Ability_Power.Spot)
dat$Ability_Mirror.Armor = as.factor(dat$Ability_Mirror.Armor)
dat$Ability_Primordial.Sea = as.factor(dat$Ability_Primordial.Sea)
dat$Ability_Prism.Armor = as.factor(dat$Ability_Prism.Armor)
dat$Ability_Protosynthesis = as.factor(dat$Ability_Protosynthesis)
dat$Ability_Punk.Rock = as.factor(dat$Ability_Punk.Rock)
dat$Ability_Pure.Power = as.factor(dat$Ability_Pure.Power)
dat$Ability_Purifying.Salt = as.factor(dat$Ability_Purifying.Salt)
dat$Ability_Quark.Drive = as.factor(dat$Ability_Quark.Drive)
dat$Ability_Quick.Draw = as.factor(dat$Ability_Quick.Draw)
dat$Ability_Receiver = as.factor(dat$Ability_Receiver)
dat$Ability_Refrigerate = as.factor(dat$Ability_Refrigerate)
dat$Ability_Ripen = as.factor(dat$Ability_Ripen)
dat$Ability_RKS.System = as.factor(dat$Ability_RKS.System)
dat$Ability_Rough.Skin = as.factor(dat$Ability_Rough.Skin)
dat$Ability_Pastel.Veil = as.factor(dat$Ability_Pastel.Veil)
dat$Ability_Sand.Force = as.factor(dat$Ability_Sand.Force)
dat$Ability_Sand.Spit = as.factor(dat$Ability_Sand.Spit)
dat$Ability_Sand.Stream = as.factor(dat$Ability_Sand.Stream)
dat$Ability_Tangling.Hair = as.factor(dat$Ability_Tangling.Hair)
dat$Ability_Grass.Pelt = as.factor(dat$Ability_Grass.Pelt)
dat$Ability_Schooling = as.factor(dat$Ability_Schooling)
dat$Ability_Costar = as.factor(dat$Ability_Costar)
dat$Ability_Seed.Sower = as.factor(dat$Ability_Seed.Sower)
dat$Ability_Shadow.Shield = as.factor(dat$Ability_Shadow.Shield)
dat$Ability_Ice.Scales = as.factor(dat$Ability_Ice.Scales)
dat$Ability_Shields.Down = as.factor(dat$Ability_Shields.Down)
dat$Ability_Skill.Lilnk = as.factor(dat$Ability_Skill.Lilnk)
dat$Ability_Slush.Rush = as.factor(dat$Ability_Slush.Rush)
dat$Ability_Soul.Heart = as.factor(dat$Ability_Soul.Heart)
dat$Ability_Stance.Change = as.factor(dat$Ability_Stance.Change)
dat$Ability_Steam.Engine = as.factor(dat$Ability_Steam.Engine)
dat$Ability_Steelworker = as.factor(dat$Ability_Steelworker)
dat$Ability_Sunction.Cups = as.factor(dat$Ability_Sunction.Cups)
dat$Ability_Supersweet.Syrup = as.factor(dat$Ability_Supersweet.Syrup)
dat$Ability_Surge.Surfer = as.factor(dat$Ability_Surge.Surfer)
dat$Ability_Truant = as.factor(dat$Ability_Truant)
dat$Ability_Propeller.Tail = as.factor(dat$Ability_Propeller.Tail)
dat$Ability_Water.Veil = as.factor(dat$Ability_Water.Veil)
dat$Ability_Sword.of.Ruin = as.factor(dat$Ability_Sword.of.Ruin)
dat$Ability_Trace = as.factor(dat$Ability_Trace)
dat$Ability_Tablets.of.Ruin = as.factor(dat$Ability_Tablets.of.Ruin)
dat$Ability_Screen.Cleaner = as.factor(dat$Ability_Screen.Cleaner)
dat$Ability_Terravolt = as.factor(dat$Ability_Terravolt)
dat$Ability_Thermal.Exchange = as.factor(dat$Ability_Thermal.Exchange)
dat$Ability_Liquid.Voice = as.factor(dat$Ability_Liquid.Voice)
dat$Ability_Touch.Claws = as.factor(dat$Ability_Touch.Claws)
dat$Ability_Toxic.Chain = as.factor(dat$Ability_Toxic.Chain)
dat$Ability_Toxic.Debris = as.factor(dat$Ability_Toxic.Debris)
dat$Ability_Transistor = as.factor(dat$Ability_Transistor)
dat$Ability_Turboblaze = as.factor(dat$Ability_Turboblaze)
dat$Ability_Unseen.Fist = as.factor(dat$Ability_Unseen.Fist)
dat$Ability_Vessel.of.Ruin = as.factor(dat$Ability_Vessel.of.Ruin)
dat$Ability_Victory.Star = as.factor(dat$Ability_Victory.Star)
dat$Ability_Volt.Absrob = as.factor(dat$Ability_Volt.Absrob)
dat$Ability_Wandering.Spirit = as.factor(dat$Ability_Wandering.Spirit)
dat$Ability_Water.Bubble = as.factor(dat$Ability_Water.Bubble)
dat$Ability_Water.Compaction = as.factor(dat$Ability_Water.Compaction)
dat$Ability_Perish.Body = as.factor(dat$Ability_Perish.Body)
dat$Ability_Well.Baked.Body = as.factor(dat$Ability_Well.Baked.Body)
dat$Ability_Wimp.Out = as.factor(dat$Ability_Wimp.Out)
dat$Ability_Wind.Power = as.factor(dat$Ability_Wind.Power)
dat$Ability_Wonder.Guard = as.factor(dat$Ability_Wonder.Guard)
dat$Ability_Zero.to.Hero = as.factor(dat$Ability_Zero.to.Hero)

get.or = function(sobj, alpha=.05) {  #This calculats the odds ratio
  b = sobj$coef[-1, 'Estimate']
  se.b = sobj$coef[-1, 'Std. Error']
  pval = sobj$coef[-1, 'Pr(>|z|)']
  or = exp(b); se.or = exp(b)*se.b
  lb = b + qnorm(alpha/2)*se.b; lb.or = exp(lb)
  ub = b + qnorm(1-alpha/2)*se.b; ub.or = exp(ub)
  out = cbind(or, se.or, lb.or, ub.or, pval)
  colnames(out) = c('OR', 'SE', paste0((1-alpha)*100, '% CI, lower'),
                    paste0((1-alpha)*100, '% CI, upper'), 'p value')
  return(out)
}

dichotomize = function(yhat, cutoff=.5) {
  out = rep(0, length(yhat))
  out[yhat > cutoff] = 1
  out
}

sen = function(ytrue, yhat) {
  ind.true1 = which(ytrue == 1)
  mean( ytrue[ind.true1] == yhat[ind.true1] )
}

spe = function(ytrue, yhat) {
  ind.true0 = which(ytrue == 0)
  mean( ytrue[ind.true0] == yhat[ind.true0] )
}
##############################################################
## what if we want to partition the data and evaluate model ##

# take 60% of data randomly as training
set.seed(8793) # set a seed so that people get the same 60% next time they run the same code
id.train = sample(1:nrow(dat), nrow(dat)*.6) # ncol() gives number of columns
id.test = setdiff(1:nrow(dat), id.train) # setdiff gives the set difference
dat.train = dat[id.train,]
dat.test = dat[id.test,]

### forward selection ###
obj = step(min.model, direction='forward', scope=max.formula) # it will print out models in each step
summary(obj) # it will give you the final model
get.or(summary(obj))

### backward elimination ###
# TO DO: implement threading; this one model took 10 hours alone to run
obj2 = step(max.model, scope=list(lower=min.model, upper=max.model), direction='backward') # start with full and end with null; reversed comparing to forward
summary(obj2) 
get.or(summary(obj2))

### step-wise selection ###
obj3 = step(min.model, scope=list(lower=min.model, upper=max.model), direction='both') # start with full and end with null
summary(obj3)
get.or(summary(obj3))

# Saving the models
saveRDS(obj, file = "C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project/forwards_model.rda")
saveRDS(obj2, file = "C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project/backwards_model.rda")
saveRDS(obj3, file = "C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project/stepwise_model.rda")

#loading the models
obj = readRDS("C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project/forwards_model.rda")
summary(obj)

obj2 = readRDS("C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project/backwards_model.rda")
summary(obj2)

obj3 = readRDS("C:/Users/Hyrek/OneDrive/Desktop/Pokedex Project/stepwise_model.rda")
summary(obj3)

## Results

# Forward
yhat = predict(obj, newdata = dat.test, type='response')
hist(yhat)

yhat.class = dichotomize(yhat, .5)
err = mean(yhat.class != dat.test$Viability) # misclassification error rate
err

table(yhat.class, dat.test$Viability)

sen(dat.test$Viability, yhat.class)
spe(dat.test$Viability, yhat.class)

# Backward
yhat2 = predict(obj2, newdata = dat.test, type='response')
hist(yhat2)

yhat2.class = dichotomize(yhat2, .5)
err = mean(yhat2.class != dat.test$Viability) # misclassification error rate
err

table(yhat2.class, dat.test$Viability)

sen(dat.test$Viability, yhat2.class)
spe(dat.test$Viability, yhat2.class)

# Step
yhat3 = predict(obj3, newdata = dat.test, type='response')
hist(yhat3)

yhat3.class = dichotomize(yhat3, .5)
err = mean(yhat3.class != dat.test$Viability) # misclassification error rate
err

table(yhat3.class, dat.test$Viability)

sen(dat.test$Viability, yhat3.class)
spe(dat.test$Viability, yhat3.class)